info:
  component: Configuration Server

spring:
  jmx:
    default_domain: cloud.config.server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/russmiles/configrepo
      health:
        repositories:
          configuredmicroservice1-dev:
            name: configuredmicroservice1
            profiles: dev

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
